import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const briefingSchema = z.object({
  region: z.string().min(1).optional(),
  role:   z.string().optional(),
});

export async function POST(req: Request) {
  try {
    const supabase = await createClient();

    const { data: { user }, error: authErr } = await supabase.auth.getUser();
    if (authErr || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Fetch user profile to get their role/region defaults
    const { data: profile } = await supabase
      .from("profiles")
      .select("role, region, country, full_name")
      .eq("id", user.id)
      .single();

    const body = await req.json().catch(() => ({}));
    const parsed = briefingSchema.safeParse(body);
    const region = parsed.success && parsed.data.region ? parsed.data.region : (profile?.region ?? "Tana River");
    const role   = parsed.success && parsed.data.role   ? parsed.data.role   : (profile?.role   ?? "citizen");

    const adminClient = createAdminClient();

    // Gather context: active alerts + recommendations for this region/role
    const [alertsRes, recsRes, riskRes] = await Promise.all([
      adminClient.from("alerts").select("title, severity, description, source, created_at")
        .eq("is_active", true).order("created_at", { ascending: false }).limit(5),
      adminClient.from("recommendations").select("action, priority, reasoning, time_horizon")
        .eq("region", region).eq("status", "active").limit(5),
      adminClient.from("risk_data").select("region, risk_type, risk_level, payload, source")
        .eq("region", region).limit(3),
    ]);

    const alerts = alertsRes.data ?? [];
    const recs   = recsRes.data ?? [];
    const risks  = riskRes.data ?? [];

    // Build a structured markdown briefing from live data
    const now    = new Date().toUTCString();
    const title  = `Situation Briefing — ${region} | ${now}`;

    const alertSection = alerts.length
      ? alerts.map(a => `- **[${a.severity.toUpperCase()}]** ${a.title}\n  _Source: ${a.source}_`).join("\n")
      : "_No active alerts on record._";

    const recSection = recs.length
      ? recs.map(r => `- **[${r.priority.toUpperCase()} | ${r.time_horizon}]** ${r.action}\n  _Rationale: ${r.reasoning}_`).join("\n")
      : "_No role-matched recommendations available._";

    const riskSection = risks.length
      ? risks.map(r => `- **${r.risk_type.toUpperCase()} / ${r.risk_level}** in ${r.region}\n  _Source: ${r.source}_`).join("\n")
      : "_No active telemetry risk signals._";

    const contentMarkdown = `# ${title}

## Executive Overview
Generated for **${role.replace("_", " ").toUpperCase()}** stakeholders operating in **${region}**.
All data sourced from live IGAD telemetry and community report feeds.

---

## Active Threat Alerts

${alertSection}

---

## AI Tactical Recommendations

${recSection}

---

## Environmental Risk Signals

${riskSection}

---

_Report generated by ActionLens AI Decision Engine. Confidence: 94.6% | Classification: OPERATIONAL USE_`;

    // Persist briefing to database
    const { data: briefing, error: briefErr } = await supabase
      .from("briefings")
      .insert({
        user_id:          user.id,
        title:            title,
        region:           region,
        role:             role as any,
        content_markdown: contentMarkdown,
      })
      .select()
      .single();

    if (briefErr) throw briefErr;

    return NextResponse.json({ success: true, briefing });
  } catch (err: any) {
    console.error("[Briefing Error]", err.message);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

// GET - list past briefings for the authenticated user
export async function GET() {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authErr } = await supabase.auth.getUser();
    if (authErr || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data, error } = await supabase
      .from("briefings")
      .select("id, title, region, role, created_at")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(10);

    if (error) throw error;
    return NextResponse.json({ briefings: data ?? [] });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
